# Generated by Django 5.1.1 on 2025-01-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_module_managers_alter_module_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='module',
            managers=[
            ],
        ),
    ]
